items = Item.create([
  { name: 'Pulled Pork Sandwich', price: 8 },
  { name: 'Mango Pulled Pork', price: 9 },
  { name: 'BBQ Chicken', price: 8 },
  { name: 'Beef Brisket', price: 8 },
  { name: 'Small BBQ Beans', price: 1 },
  { name: 'Small Vegetarian Beans', price: 1 },
  { name: 'Large BBQ Beans', price: 4 },
  { name: 'Large BBQ Beans', price: 4 },
  { name: 'Small Potato Salad', price: 1 },
  { name: 'Large Potato Salad', price: 4 },
  { name: 'Small Collard Greens', price: 1 },
  { name: 'Large Collard Greens', price: 4 },
  { name: 'Small Sticky Rice', price: 1 },
  { name: 'Large Sticky Rice', price: 4 },
  { name: 'Small Coleslaw', price: 1 },
  { name: 'Large Coleslaw', price: 4 },
  { name: 'Small Cornbread', price: 1 },
  { name: 'Large Cornbread', price: 4 },
  { name: 'BBQ Chicken', price: 9 },
  { name: 'Chicken Ceaser', price: 9 },
  { name: 'Dinner Salad', price: 3 },
  { name: 'Dinner Ceasar', price: 3 },
  { name: 'Pork Sampler Reg', price: 15 },
  { name: 'Beef Sampler Reg', price: 15 },
  { name: 'Chicken Sampler Reg', price: 15 },
  { name: 'Rib Sampler Reg', price: 15 },
  { name: 'Pork Sampler Deluxe', price: 20 },
  { name: 'Beef Sampler Deluxe', price: 20 },
  { name: 'Chicken Sampler Deluxe', price: 20 },
  { name: 'Rib Sampler Deluxe', price: 20 },
  { name: 'Single Rib', price: 3 },
  { name: '1/4 Rack (3 Ribs)', price: 9 },
  { name: '1/2 Rack (6 Ribs)', price: 15 },
  { name: 'Full Rack', price: 26 },
  { name: 'Soda', price: 1 },
])